### PR TITLE
Fix issue in relay class

### PR DESCRIPTION
**Pull request by kriptonix**
In Relay class we are trying to decode WebSocket object so it doesn't work. The line `$response = json_decode($response);` doesn't work, we need to decode the content and not the object so I have changed the line to `$response = json_decode($response->getContent());`

### CODE REVIEW

**Comment by Sebastix** [comment]
@kriptonix I see the problem. Is it correct in this PR / new added code this function is not being called anywhere?

**Comment by kriptonix** [comment]
I don't understand what you mean with "Is it correct in this PR / new added code this function is not being called anywhere?". I just changed one line adding "->getContent()"?

**Comment by kriptonix** [comment]
Yes, this has nothing to do with #55. This is just a change to the existing code not related to reading from relay feature

**Comment by Sebastix** [comment]
Responses from relays can be improved a lot, they are now wrapped in a 'incomplete' and quite abstract `CommandResult` object.
My idea for handling the relay responses in a more structered way following the NIP-01 specs:

- RelayResponse class
    - type
    - RelayReponseEvent class (extends RelayResponse)
        - subscription_id
        - event (JSON string)
    - RelayReponseOk class (extends RelayResponse)
        - event_id
        - true|false
        - message
    - RelayResponseEose class
        - subscription_id
    - RelayReponseClosed class (extends RelayResponse)
        - subscription_id
        - message
    - RelayReponseNotice class (extends RelayResponse)
        - message
       
This will also cover the responses which can be served to clients from a websocket server.

**Comment by Sebastix** [comment]
@kriptonix What do you think of closing this PR as the plan is to do rewrite / integrate better responses from relays?

**Comment by kriptonix** [comment]
Sorry for late reply, I somehow missed this message of yours. You can close this PR since I implemented response handling and made a new PR for you to check out.

**Pull request closed without merging**
